import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function BMW(props) {
    const ref = useRef()
  const { nodes, materials } = useGLTF('/dullatjatt/bmw.glb')
  useFrame((state, delta) => {
    ref.current.rotation.y -= delta * 0.1
  })
  return (
    <group {...props} dispose={null} position={[0,-.6,0]} rotation={[0,2.5,0]} ref={ref}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.body_body_chrome_0.geometry}
            material={materials.body_chrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.body_body_focus_0.geometry}
            material={materials.body_focus}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.body_body_paint_0.geometry}
            material={materials.body_paint}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.body_body_plastic_0.geometry}
            material={materials.body_plastic}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.body_body_print_0.geometry}
            material={materials.body_print}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.body_mirror_0.geometry}
            material={materials.mirror}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.body_win_frame_0.geometry}
            material={materials.win_frame}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.body_win_0.geometry}
            material={materials.material}
          />
        </group>
        <group position={[-75.477, 34.296, -140.571]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.brake_FL_disk_brake_tr007_0.geometry}
            material={materials['disk_brake_tr.007']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.brake_FL_disk_brake007_0.geometry}
            material={materials['disk_brake.007']}
          />
        </group>
        <group position={[75.477, 34.296, -140.571]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.brake_FR_disk_brake_tr006_0.geometry}
            material={materials['disk_brake_tr.006']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.brake_FR_disk_brake006_0.geometry}
            material={materials['disk_brake.006']}
          />
        </group>
        <group position={[-75.477, 34.287, 139.504]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.brake_RL_disk_brake_tr005_0.geometry}
            material={materials['disk_brake_tr.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.brake_RL_disk_brake005_0.geometry}
            material={materials['disk_brake.005']}
          />
        </group>
        <group position={[75.477, 34.287, 139.504]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.brake_RR_disk_brake_tr004_0.geometry}
            material={materials['disk_brake_tr.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.brake_RR_disk_brake004_0.geometry}
            material={materials['disk_brake.004']}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.focus_int_mirror_int_focus_0.geometry}
            material={materials['mirror_int._focus']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.focus_int_mirror_int_0.geometry}
            material={materials['mirror_int.']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.focus_int_tree_rope_0.geometry}
            material={materials.tree_rope}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.focus_int_tree_0.geometry}
            material={materials.tree}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.front_lights_alum_0.geometry}
            material={materials.alum}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.front_lights_Material001_0.geometry}
            material={materials['Material.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.front_lights_Material003_0.geometry}
            material={materials['Material.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.front_lights_Material013_0.geometry}
            material={materials['Material.013']}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.headlight_headlight_signal_lights_0.geometry}
            material={materials.headlight_signal_lights}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.headlight_headlight_0.geometry}
            material={materials.headlight}
          />
        </group>
        <group position={[75.477, 33.808, 138.656]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_FL_bbs_tex004_0.geometry}
            material={materials['bbs_tex.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_FL_blt004_0.geometry}
            material={materials['blt.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_FL_disk_paint004_0.geometry}
            material={materials['disk_paint.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_FL_disk004_0.geometry}
            material={materials['disk.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_FL_tire004_0.geometry}
            material={materials['tire.004']}
          />
        </group>
        <group position={[-75.477, 33.808, 138.656]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_FR_bbs_tex002_0.geometry}
            material={materials['bbs_tex.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_FR_blt002_0.geometry}
            material={materials['blt.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_FR_disk_paint002_0.geometry}
            material={materials['disk_paint.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_FR_disk002_0.geometry}
            material={materials['disk.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_FR_tire002_0.geometry}
            material={materials['tire.002']}
          />
        </group>
        <group position={[75.477, 33.808, -141.389]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_RL_bbs_tex003_0.geometry}
            material={materials['bbs_tex.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_RL_blt003_0.geometry}
            material={materials['blt.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_RL_disk_paint003_0.geometry}
            material={materials['disk_paint.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_RL_disk003_0.geometry}
            material={materials['disk.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_RL_tire003_0.geometry}
            material={materials['tire.003']}
          />
        </group>
        <group position={[-76.425, 33.808, -141.389]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_RR_bbs_tex_0.geometry}
            material={materials.bbs_tex}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_RR_blt_0.geometry}
            material={materials.material_35}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_RR_disk_paint_0.geometry}
            material={materials.disk_paint}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_RR_disk_0.geometry}
            material={materials.disk}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_RR_tire_0.geometry}
            material={materials.tire}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.logo_bmw_logo_0.geometry}
          material={materials.bmw_logo}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['��������������_������'].geometry}
          material={materials['.002']}
          scale={[0.329, 0.329, 1.228]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/dullatjatt/bmw.glb')